import turtle

turtle.penup()
turtle.goto(-300,-25)
turtle.pendown()
turtle.color("", "grey30")
turtle.begin_fill()
turtle.forward(60)
turtle.left(120)
turtle.forward(60)
turtle.left(120)
turtle.forward(60)
turtle.end_fill()

turtle.penup()
turtle.left(120)
turtle.forward(120)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.forward(120)
turtle.pendown()
turtle.color("black", "grey45")
turtle.begin_fill()
turtle.forward(60)
turtle.left(72)
turtle.forward(60)
turtle.left(72)
turtle.forward(60)
turtle.left(72)
turtle.forward(60)
turtle.left(72)
turtle.forward(60)
turtle.left(72)
turtle.end_fill()

turtle.penup()
turtle.forward(120)
turtle.pendown()
turtle.color("black", "grey90")
turtle.begin_fill()
turtle.forward(60)
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.end_fill()

turtle.penup()
turtle.forward(150)
turtle.color("black", "grey30")
turtle.begin_fill()
turtle.pendown()
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)

turtle.end_fill()
turtle.done()