name = input("enter Employee's name:")
Hours = eval(input("Enter number of hours worked in a week:"))
Rate=eval(input("Enter hourly pay rate:"))
Fed_tax=eval(input("Enter federal tax withholding rate:"))
St_tax=eval( input("Enter state tax withholding rate:"))
Income=Hours*Rate
print("Employee Name:",name)
print("Hours Worked:",Hours)
print("Pay Rate:",Rate)
print("Gross Pay:",Income)
print("Deductions:\n\t")
print("\t Federal Withholding (20.0%) $",Fed_tax*Income)
print("\t State Withholding (9.0%) $",St_tax*Income)
print("\t Total Deduction: $",(St_tax*Income)+(Fed_tax*Income))
print("Net Pay: $" ,(Income-((St_tax*Income)+(Fed_tax*Income))))